[package]
name = "sflk"
version = "0.1.0"
authors = ["anima-libera <anim.libera@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/anima-libera/sflk"
description = "SFLK programming language"

[dependencies]
